---
- name: Configure MongoDB
  hosts: db
  tags: db-tag
  become: true

  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Change mongo config file
      become: yes
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644
      tags: db-tag
      notify: restart mongo

  handlers:
    - name: restart mongo
      become: yes
      service: name=mongod state=restarted

- name: Configure hosts and deploy application
  hosts: app
  tags: app-tag
  become: true

  vars:
    db_host: 10.132.0.2

  tasks:
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload puma

    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/appuser/db_config

    - name: Enable puma
      systemd: name=puma enabled=yes

  handlers:
  - name: reload puma
    become: yes
    systemd: name=puma state=restarted

- name: Deploy app
  hosts: app
  tags: deploy-tag

  tasks:
    - name: Fetch the latest version of application code
      git:
        repo: https://github.com/express42/reddit.git
        dest: /home/appuser/reddit
        version: monolith
      tags: deploy-tag
      notify: reload puma

    - name: Bundle install
      bundler:
        state: present
        chdir: /home/appuser/reddit
      tags: deploy-tag

  handlers:
    - name: reload puma
      become: yes
      systemd: name=puma state=restarted
